apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-html
  template:
    metadata:
      labels:
        app: test-html
    spec:
      containers:
      - name: test-html-container
        image: mytestacrjenkins.azurecr.io/test-html-app:BUILD_TAG
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-html-service
spec:
  type: LoadBalancer
  selector:
    app: test-html
  ports:
  - port: 80
    targetPort: 80

